AWSTemplateFormatVersion: '2010-09-09'

Description: Create an S3 Bucket using CloudFormation

Resources:
  MyBucket:
    Type: AWS::S3::Bucket

# Outputs:
#   BucketName:
#     Description: Name of the bucket
#     Value: !Ref MyBucket